//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMT.Controls.WinForms.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TMT.Controls.WinForms.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design Issue.
        /// </summary>
        public static string DESIN_ERROR {
            get {
                return ResourceManager.GetString("DESIN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Connected Control.
        /// </summary>
        public static string DESIN_ERROR_NoConnectedControl {
            get {
                return ResourceManager.GetString("DESIN_ERROR_NoConnectedControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error adding new.
        /// </summary>
        public static string ERROR_AddingNew {
            get {
                return ResourceManager.GetString("ERROR_AddingNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Logging In.
        /// </summary>
        public static string ERROR_ApplicationLogin {
            get {
                return ResourceManager.GetString("ERROR_ApplicationLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ERROR_BW_Issue {
            get {
                return ResourceManager.GetString("ERROR_BW_Issue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Cell Click.
        /// </summary>
        public static string ERROR_CellClick {
            get {
                return ResourceManager.GetString("ERROR_CellClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Error at Column: {0}, Row: {1}.
        /// </summary>
        public static string ERROR_CellDataError {
            get {
                return ResourceManager.GetString("ERROR_CellDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Cell Validation.
        /// </summary>
        public static string ERROR_CellValidation {
            get {
                return ResourceManager.GetString("ERROR_CellValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Clearing data.
        /// </summary>
        public static string ERROR_ClearingData {
            get {
                return ResourceManager.GetString("ERROR_ClearingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Closing Calendar.
        /// </summary>
        public static string ERROR_CloseCalendar {
            get {
                return ResourceManager.GetString("ERROR_CloseCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Showing column manager.
        /// </summary>
        public static string ERROR_ColumnManager {
            get {
                return ResourceManager.GetString("ERROR_ColumnManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column [{0}] does not have a ValueType.
        /// </summary>
        public static string ERROR_ColumValueTypeMissing {
            get {
                return ResourceManager.GetString("ERROR_ColumValueTypeMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error duplicating.
        /// </summary>
        public static string ERROR_DuplicatingNew {
            get {
                return ResourceManager.GetString("ERROR_DuplicatingNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Filtering Values.
        /// </summary>
        public static string ERROR_FilteringLovValues {
            get {
                return ResourceManager.GetString("ERROR_FilteringLovValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading data to the window.
        /// </summary>
        public static string ERROR_LoadingData {
            get {
                return ResourceManager.GetString("ERROR_LoadingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database must have a value.
        /// </summary>
        public static string ERROR_LoginDialog_DatabaseNameEmpty {
            get {
                return ResourceManager.GetString("ERROR_LoginDialog_DatabaseNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port must have value.
        /// </summary>
        public static string ERROR_LoginDialog_DatabaseServerPort {
            get {
                return ResourceManager.GetString("ERROR_LoginDialog_DatabaseServerPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete Information.
        /// </summary>
        public static string ERROR_LoginDialog_Header {
            get {
                return ResourceManager.GetString("ERROR_LoginDialog_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LDAP server is not reachable, please check your connection properties.
        /// </summary>
        public static string ERROR_LoginDialog_LDAP {
            get {
                return ResourceManager.GetString("ERROR_LoginDialog_LDAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LDAP URL must have a value.
        /// </summary>
        public static string ERROR_LoginDialog_LDAPServerUrlEmpty {
            get {
                return ResourceManager.GetString("ERROR_LoginDialog_LDAPServerUrlEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LDAP User Not Found..
        /// </summary>
        public static string ERROR_LoginDialog_LDAPUserNotFound {
            get {
                return ResourceManager.GetString("ERROR_LoginDialog_LDAPUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must have a value.
        /// </summary>
        public static string ERROR_LoginDialog_PasswordEmpty {
            get {
                return ResourceManager.GetString("ERROR_LoginDialog_PasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server must have a value.
        /// </summary>
        public static string ERROR_LoginDialog_ServerUrlEmpty {
            get {
                return ResourceManager.GetString("ERROR_LoginDialog_ServerUrlEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Id must have a value.
        /// </summary>
        public static string ERROR_LoginDialog_UserIdEmpty {
            get {
                return ResourceManager.GetString("ERROR_LoginDialog_UserIdEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Going Back.
        /// </summary>
        public static string ERROR_NavigationBack {
            get {
                return ResourceManager.GetString("ERROR_NavigationBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Loading Panel.
        /// </summary>
        public static string ERROR_PanelLoadIssue {
            get {
                return ResourceManager.GetString("ERROR_PanelLoadIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reloading data to the window.
        /// </summary>
        public static string ERROR_ReLoadingData {
            get {
                return ResourceManager.GetString("ERROR_ReLoadingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Removing.
        /// </summary>
        public static string ERROR_Removing {
            get {
                return ResourceManager.GetString("ERROR_Removing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving data.
        /// </summary>
        public static string ERROR_SavingData {
            get {
                return ResourceManager.GetString("ERROR_SavingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Validating data before Save.
        /// </summary>
        public static string ERROR_SavingDataValidation {
            get {
                return ResourceManager.GetString("ERROR_SavingDataValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Loading List of Values.
        /// </summary>
        public static string ERROR_SearchDialogListOfValueLoading {
            get {
                return ResourceManager.GetString("ERROR_SearchDialogListOfValueLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error setting selected date.
        /// </summary>
        public static string ERROR_SetSelectedDate {
            get {
                return ResourceManager.GetString("ERROR_SetSelectedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Showing Calendar.
        /// </summary>
        public static string ERROR_ShowCalendar {
            get {
                return ResourceManager.GetString("ERROR_ShowCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory Value Missing.
        /// </summary>
        public static string Exclamation_MandatoryEmpty {
            get {
                return ResourceManager.GetString("Exclamation_MandatoryEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; value missing.
        /// </summary>
        public static string Exclamation_MandatoryValueEmpty {
            get {
                return ResourceManager.GetString("Exclamation_MandatoryValueEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data found.
        /// </summary>
        public static string Exclamation_NoDataFound {
            get {
                return ResourceManager.GetString("Exclamation_NoDataFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data found, Try changing search condition. .
        /// </summary>
        public static string Exclamation_NoDataFoundText {
            get {
                return ResourceManager.GetString("Exclamation_NoDataFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] fontawesome_webfont {
            get {
                object obj = ResourceManager.GetObject("fontawesome_webfont", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes.
        /// </summary>
        public static string MSG_HEADER_Save {
            get {
                return ResourceManager.GetString("MSG_HEADER_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Loading LOV data.
        /// </summary>
        public static string MSG_LOV_LoadError {
            get {
                return ResourceManager.GetString("MSG_LOV_LoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Setting LOV data.
        /// </summary>
        public static string MSG_LOV_SetError {
            get {
                return ResourceManager.GetString("MSG_LOV_SetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Changes Found.
        /// </summary>
        public static string MSG_SAVE_Null {
            get {
                return ResourceManager.GetString("MSG_SAVE_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        public static string MSG_SAVE_Saved {
            get {
                return ResourceManager.GetString("MSG_SAVE_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Changes Found.
        /// </summary>
        public static string MSG_SAVE_SaveIssue {
            get {
                return ResourceManager.GetString("MSG_SAVE_SaveIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string QUESTION_Delete {
            get {
                return ResourceManager.GetString("QUESTION_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; will be removed. Are you sure ?.
        /// </summary>
        public static string QUESTION_DeleteConfirm {
            get {
                return ResourceManager.GetString("QUESTION_DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected rows will be delete. Are you sure?.
        /// </summary>
        public static string QUESTION_DeleteConfirmAll {
            get {
                return ResourceManager.GetString("QUESTION_DeleteConfirmAll", resourceCulture);
            }
        }
    }
}
